language: python

python:
  - "3.3"
  - "3.4"

addons:
  apt:
    packages:
    - colordiff

install:
  - "pip install -r requirements.txt"

script:
  - python --version
  - PYTHONPATH=scripts green tests/ --quiet-stdout
  - autopep8 --diff -r scripts/ | colordiff
  - autopep8 --diff -r tests/ | colordiff
  - autopep8 --diff setup.py | colordiff
  - flake8 scripts/ tests/ setup.py
