---
shortcuts:
- name: Open RH bugzilla Bug
  match: BZ{}
  shell: |
    xdg-open https://bugzilla.redhat.com/show_bug.cgi?id={}

- name: Clone github repo
  match: https://github.com/{}/{}
  shell: |
    cd /tmp/
    git clone git@github.com:{}/{}.git

- name: Get NVR
  regex: (\w+)-(\w+)-(\w+)$
  shell: |
    echo "name: {0}, version: {1}, release: {2} l1"
  label: l1

- name: Get NVR2
  regex: (\w+)-(\w+)-(\w+)$
  shell: |
    echo "name: {0}, version: {1}, release: {2} l2"
  label: l2
