---
shortcuts:
- name: Open RH bugzilla Bug
  match: BZ{}
  shell: |
    xdg-open https://bugzilla.redhat.com/show_bug.cgi?id={}
  label: bug

- name: Clone a Github repo to temp directory
  regex: ^https://github.com/([\w-]+)/([\w-]+).*$
  shell: |
    pushd /tmp/
    git clone git@github.com:{0}/{1}.git
    cd {1}
  label:
  - tmp
  - clone

- name: Clone a Github pull request
  regex: ^https://github.com/([\w-]+)/([\w-]+)/pull/([0-9]+)$
  shell: |
    pushd /tmp/
    git clone git@github.com:{0}/{1}.git
    cd {1}
    git fetch origin pull/{2}/head:pr-{2}
    git checkout pr-{2}
  label:
  - pull
  - clone

- name: Edit .bashrc
  regex: ^bashrc$
  shell: vim ~/.bashrc
  label:
  - edit
  - bashrc

- name: Backup .bashrc
  regex: ^bashrc$
  shell: |
    mkdir -p /tmp/backup
    cp ~/.bashrc /tmp/backup
  label:
  - backup
  - bashrc
